### ISSUE TITLE
Option to pass in properties  when dispatching the action

### ISSUE THREAD

**Issue by JakeDluhy** [suciuvlad/redux-dialog#2]
I was wondering what your thoughts are on adding the option to pass in properties to a modal when dispatching the action to open it. We have a case where the information within the modal is contextual to the previous event.

Added a PR for it as well =)

**Comment by suciuvlad** [comment]
@JakeDluhy Sorry for the late reply. Could you provide an example?

**Comment by JakeDluhy** [comment]
From the README in the PR:
 
 When dispatching the action to open the dialog, adding a payload as the second parameter to `openDialog` will be available within the dialog as the `payload` property.
 ```js
 dispatch(openDialog('accountDialog', { accountName: 'My Account' }));
 
 const BasicDialog = ({ payload }) => (
   <div>
     {payload.accountName}
   </div>
   <div>
     My awesome modalbox!
   </div>
 )
 ```

**Comment by suciuvlad** [comment]
@JakeDluhy Why not let BasicDialog fetch the data on its own?

```js
 const BasicDialog = ({ payload }) => (
   <div>
     {payload.accountName}
   </div>
   <div>
     My awesome modalbox!
   </div>
 )

const mapStateToProps = (state) => {(
  accountName: state.accountName
)}

connect(mapStateToProps)(BasicDialog)
```

You can also send props directly:
```js
<BasicDialog accountName={ 'My Account' } />
```

**Comment by JakeDluhy** [comment]
The workflow for this was create account page => submit => redirect to accounts index page => display modal with a success message. That modal needs the account name, and now we are on the accounts index page, which means we don't have any context as to account id, etc... Therefore we are unable to access it from the store

**Comment by nhagen** [comment]
Running into this sort of problem as well: A has many of B, a global dropdown nav lets you create Bs under any of the As with a plus sign next to each A--there is no global state representing that the user is in the context of a specific A.

**Comment by nhagen** [comment]
Tried the router approach, and it worked well to get the modal up but I ran into several issues with closing the modal. I had to pass `onRequestClose` to the component when I would have preferred it to be in the hoc call `reduxDialog` (it wasn't getting called when I did that), and then I was having issues with my sidebar when I navigated back on `onRequestClose`. Even if it did work, it really added a lot of complexity that isn't quite worth it for us right now. Being able to pass in the needed info with the action would be helpful.

**Comment by JakeDluhy** [comment]
I have another use case for this: I have a list of users, and the modal that is shown needs to be specific to the user. So the action to open the modal needs to pass in the user object.

If I rebase my branch would you be willing to accept the PR?

**Comment by JakeDluhy** [comment]
I was frustrated with the unresponsiveness. I've published https://www.npmjs.com/package/redux-dialog-extended off of my fork and will be actively maintaining it.
