### ISSUE TITLE
Test coverage?

### ISSUE THREAD

**Issue by et** [suciuvlad/redux-dialog#9]
Any ideas on how to test this? 
Since this project is fairly small, I was hoping to use it as a guideline on how to test an HOC at a small scale.

**Comment by suciuvlad** [comment]
@et I just added some basic tests. Perhaps that helps. The harder part is the fact that usually the HOC returns a connected component and you have to mock the redux store. For that you could use something like https://github.com/arnaudbenard/redux-mock-store. You could also independently test your component by exposing it as a named export.

**Comment by et** [comment]
Thanks @suciuvlad. `redux-mock-store` is the way to go 😄
